services:
  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    env_file:
      - ../.env
    volumes:
      - ./promtail.yml:/etc/promtail/config.yml
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    command: -config.file=/etc/promtail/config.yml -config.expand-env=true -log.level=error
    restart: unless-stopped